# herdr — upstream-owned Omarchy binary: a terminal workspace manager for
# AI coding agents (tmux-alike shipped alongside tmux since v4.0.0; SUPER+CTRL+RETURN
# opens it, `alias h=herdr`, `hdl/hds/hdlm/hsl` dev-layout helpers).
# Vendored because nixpkgs does not ship a herdr package (checked 2026-08-18
# against the 26.05 pin and unstable). The vendored omarchy tree seeds its
# config via omarchy-refresh-config herdr/config.toml; nothing else to wire.
#
# Build mirrors upstream's own nix/package.nix: the Rust build script
# compiles the vendored libghostty-vt terminal parser with Zig, feeding it
# the zon dependencies as a --system dir (build.zig.zon.nix is generated by
# zon2nix and shipped in the repo) so the sandbox build never fetches.
{
  lib,
  stdenv,
  rustPlatform,
  fetchFromGitHub,
  fetchzip,
  fetchurl,
  fetchgit,
  zig_0_15,
  zstd,
  pkg-config,
  runCommand,
}:

let
  zigDeps = import "${src}/vendor/libghostty-vt/build.zig.zon.nix" {
    inherit
      lib
      fetchzip
      fetchurl
      fetchgit
      zig_0_15
      zstd
      ;
    runCommandLocal = runCommand;
    # linkFarm flattened to a single output dir, as upstream's
    # nix/package.nix does (cp -rL of every entry under $out/<name>).
    linkFarm =
      name: entries:
      runCommand name { } ''
        mkdir -p $out
        ${lib.concatMapStringsSep "\n" (entry: ''
          cp -rL ${entry.path} $out/${entry.name}
        '') entries}
      '';
  };

  src = fetchFromGitHub {
    owner = "omacom-io";
    repo = "herdr";
    rev = "v0.8.0";
    hash = "sha256-empFQ+hrnCh2JhOzQRWSCLV0YoZC3DXW3bY6k8YuJjk=";
  };
in
rustPlatform.buildRustPackage (finalAttrs: {
  pname = "herdr";
  version = "0.8.0";

  inherit src;

  cargoHash = "sha256-E1lBgpTFZwNjeALeg/atwbDFL/XQbUnvCdX7ohbAHAc=";

  nativeBuildInputs = [
    zig_0_15
    pkg-config
  ];

  # zig's setup-hook (26.05) replaces buildPhase with zigBuildPhase when no
  # phase is pre-set, which would clobber cargoBuildHook and run a bare
  # `zig build` at the crate root (no build.zig there — build.rs is the
  # driver). Keep every stdenv phase cargo's.
  dontUseZigConfigure = true;
  dontUseZigBuild = true;
  dontUseZigCheck = true;
  dontUseZigInstall = true;

  env = {
    LIBGHOSTTY_VT_OPTIMIZE = "ReleaseFast";
    LIBGHOSTTY_VT_SIMD = "true";
    LIBGHOSTTY_VT_ZIG_SYSTEM_DIR = zigDeps;
    ZIG = lib.getExe zig_0_15;
  };

  preBuild = ''
    export ZIG_GLOBAL_CACHE_DIR="$TMPDIR/zig-global-cache"
    export ZIG_LOCAL_CACHE_DIR="$TMPDIR/zig-local-cache"
  '';

  doCheck = false;

  meta = {
    description = "Terminal workspace manager for AI coding agents (Omarchy)";
    homepage = "https://herdr.dev";
    license = lib.licenses.asl20;
    platforms = lib.platforms.linux;
    mainProgram = "herdr";
  };
})
